global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # IntelliJ에서 실행 중인 앱을 host.docker.internal 로 스크랩
  - job_name: 'hrguard-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'hrguard-batch'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
